name = "pokemonRanBats"
uuid = "67ceef4b-49f4-420f-a236-6963ba6d617b"
authors = ["MKollmann"]
version = "1.0.0-DEV"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
